name: couchbase-tests
run-name: Run Couchbase Tests
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: Install Docker Go SDK
        run: |
          go run main.go

